### ISSUE TITLE
Music matching issue

### ISSUE THREAD

**Issue by skarllot** [ianloic/rdio-export#3]
The rdio-export could not find matching music for:
- http://www.rdio.com/artist/York/album/Planet_Chill_2014-01/track/Balearic_Sunrise_(Max_Denoise__Harnam_Remix)/
- http://www.rdio.com/artist/York/album/Planet_Chill_2014-01/track/Lose_Sight/
- http://www.rdio.com/artist/Ferry_Corsten/album/Once_Upon_A_Night/track/Saona_(Andy_Duguid_Remix)/

**Comment by ianloic** [comment]
Do these tracks exist in Google Play Music?

**Comment by ianloic** [comment]
So it looks like the two tracks on Planet Chill 2014-01 are tagged too differently on Play Music to be matched automatically. You can add them manually.

The Ferry Corsten track isn't available (in the US at least) on Rdio and doesn't seem to be available (in the US) on Play either. Again if you can find it then add it manually

My script does its best but is also a little timid about matching tracks that appear to have completely different artists since they're often garbage versions of tracks. Dance music unfortunately has a tendency to fall foul of my tricks though. Sorry! I hope this script was helpful nonetheless.
